// Code generated by MockGen. DO NOT EDIT.
// Source: app.modules/core/moderatorbot (interfaces: MessageBot)
//
// Generated by this command:
//
//	mockgen app.modules/core/moderatorbot MessageBot
//

// Package mock_moderatorbot is a generated GoMock package.
package mock_moderatorbot

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageBot is a mock of MessageBot interface.
type MockMessageBot struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBotMockRecorder
	isgomock struct{}
}

// MockMessageBotMockRecorder is the mock recorder for MockMessageBot.
type MockMessageBotMockRecorder struct {
	mock *MockMessageBot
}

// NewMockMessageBot creates a new mock instance.
func NewMockMessageBot(ctrl *gomock.Controller) *MockMessageBot {
	mock := &MockMessageBot{ctrl: ctrl}
	mock.recorder = &MockMessageBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBot) EXPECT() *MockMessageBotMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockMessageBot) SendMessage(ctx context.Context, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockMessageBotMockRecorder) SendMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockMessageBot)(nil).SendMessage), ctx, message)
}

// SendMessageWithError mocks base method.
func (m *MockMessageBot) SendMessageWithError(ctx context.Context, message string, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageWithError", ctx, message, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageWithError indicates an expected call of SendMessageWithError.
func (mr *MockMessageBotMockRecorder) SendMessageWithError(ctx, message, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageWithError", reflect.TypeOf((*MockMessageBot)(nil).SendMessageWithError), ctx, message, err)
}
