import { RoomLayout } from '../../types/room-layout'

export const circleRoom: RoomLayout = {
    font_size_ratio: 0.018,
    floor_image: '',
    room_shape: {
        width: 330,
        height: 230,
    },
    seat_shape: {
        width: 35,
        height: 25,
    },
    partition_shapes: [
        {
            name: 'v30',
            width: 5,
            height: 30,
        },
        {
            name: 'h40',
            width: 40,
            height: 5,
        },
        {
            name: 'v140',
            width: 5,
            height: 140,
        },
        {
            name: 'h210',
            width: 210,
            height: 5,
        },
        {
            name: 'v35',
            width: 5,
            height: 35,
        },
        {
            name: 'h35',
            width: 35,
            height: 5,
        },
    ],
    seats: [
        {
            id: 1,
            x: 0,
            y: 0,
            rotate: 0,
        },
        {
            id: 2,
            x: 40,
            y: 0,
            rotate: 0,
        },
        {
            id: 3,
            x: 80,
            y: 0,
            rotate: 0,
        },
        {
            id: 4,
            x: 120,
            y: 0,
            rotate: 0,
        },
        {
            id: 5,
            x: 160,
            y: 0,
            rotate: 0,
        },
        {
            id: 6,
            x: 200,
            y: 0,
            rotate: 0,
        },
        {
            id: 7,
            x: 240,
            y: 0,
            rotate: 0,
        },
        {
            id: 8,
            x: 295,
            y: 0,
            rotate: 0,
        },
        {
            id: 9,
            x: 295,
            y: 30,
            rotate: 0,
        },
        {
            id: 10,
            x: 295,
            y: 60,
            rotate: 0,
        },
        {
            id: 11,
            x: 295,
            y: 90,
            rotate: 0,
        },
        {
            id: 12,
            x: 295,
            y: 120,
            rotate: 0,
        },
        {
            id: 13,
            x: 295,
            y: 150,
            rotate: 0,
        },
        {
            id: 14,
            x: 295,
            y: 205,
            rotate: 0,
        },
        {
            id: 15,
            x: 255,
            y: 205,
            rotate: 0,
        },
        {
            id: 16,
            x: 215,
            y: 205,
            rotate: 0,
        },
        {
            id: 17,
            x: 175,
            y: 205,
            rotate: 0,
        },
        {
            id: 18,
            x: 135,
            y: 205,
            rotate: 0,
        },
        {
            id: 19,
            x: 95,
            y: 205,
            rotate: 0,
        },
        {
            id: 20,
            x: 55,
            y: 205,
            rotate: 0,
        },
        {
            id: 21,
            x: 0,
            y: 205,
            rotate: 0,
        },
        {
            id: 22,
            x: 0,
            y: 175,
            rotate: 0,
        },
        {
            id: 23,
            x: 0,
            y: 145,
            rotate: 0,
        },
        {
            id: 24,
            x: 0,
            y: 115,
            rotate: 0,
        },
        {
            id: 25,
            x: 0,
            y: 85,
            rotate: 0,
        },
        {
            id: 26,
            x: 0,
            y: 55,
            rotate: 0,
        },
        {
            id: 27,
            x: 60,
            y: 50,
            rotate: 0,
        },
        {
            id: 28,
            x: 115,
            y: 50,
            rotate: 0,
        },
        {
            id: 29,
            x: 155,
            y: 50,
            rotate: 0,
        },
        {
            id: 30,
            x: 195,
            y: 50,
            rotate: 0,
        },
        {
            id: 31,
            x: 235,
            y: 50,
            rotate: 0,
        },
        {
            id: 32,
            x: 235,
            y: 95,
            rotate: 0,
        },
        {
            id: 33,
            x: 235,
            y: 125,
            rotate: 0,
        },
        {
            id: 34,
            x: 235,
            y: 155,
            rotate: 0,
        },
        {
            id: 35,
            x: 180,
            y: 155,
            rotate: 0,
        },
        {
            id: 36,
            x: 140,
            y: 155,
            rotate: 0,
        },
        {
            id: 37,
            x: 100,
            y: 155,
            rotate: 0,
        },
        {
            id: 38,
            x: 60,
            y: 155,
            rotate: 0,
        },
        {
            id: 39,
            x: 60,
            y: 110,
            rotate: 0,
        },
        {
            id: 40,
            x: 60,
            y: 80,
            rotate: 0,
        },
        {
            id: 41,
            x: 120,
            y: 100,
            rotate: 0,
        },
        {
            id: 42,
            x: 175,
            y: 105,
            rotate: 0,
        },
    ],
    partitions: [
        {
            id: 1,
            x: 35,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 2,
            x: 75,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 3,
            x: 115,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 4,
            x: 155,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 5,
            x: 195,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 6,
            x: 235,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 7,
            x: 275,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 8,
            x: 290,
            y: 25,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 9,
            x: 290,
            y: 55,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 10,
            x: 290,
            y: 85,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 11,
            x: 290,
            y: 115,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 12,
            x: 290,
            y: 145,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 13,
            x: 290,
            y: 175,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 14,
            x: 290,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 15,
            x: 250,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 16,
            x: 210,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 17,
            x: 170,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 18,
            x: 130,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 19,
            x: 90,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 20,
            x: 50,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 21,
            x: 0,
            y: 200,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 22,
            x: 0,
            y: 170,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 23,
            x: 0,
            y: 140,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 24,
            x: 0,
            y: 110,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 25,
            x: 0,
            y: 80,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 26,
            x: 0,
            y: 50,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 27,
            x: 55,
            y: 45,
            shape_type: 'v140',
            rotate: 0,
        },
        {
            id: 28,
            x: 60,
            y: 45,
            shape_type: 'h210',
            rotate: 0,
        },
        {
            id: 29,
            x: 270,
            y: 45,
            shape_type: 'v140',
            rotate: 0,
        },
        {
            id: 30,
            x: 60,
            y: 180,
            shape_type: 'h210',
            rotate: 0,
        },
        {
            id: 31,
            x: 60,
            y: 75,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 32,
            x: 110,
            y: 50,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 33,
            x: 150,
            y: 50,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 34,
            x: 190,
            y: 50,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 35,
            x: 230,
            y: 50,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 36,
            x: 230,
            y: 90,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 37,
            x: 230,
            y: 120,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 38,
            x: 230,
            y: 150,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 39,
            x: 215,
            y: 150,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 40,
            x: 175,
            y: 150,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 41,
            x: 135,
            y: 150,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 42,
            x: 95,
            y: 150,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 43,
            x: 60,
            y: 135,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 44,
            x: 60,
            y: 105,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 45,
            x: 115,
            y: 95,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 46,
            x: 120,
            y: 95,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 47,
            x: 155,
            y: 95,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 48,
            x: 170,
            y: 100,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 49,
            x: 175,
            y: 130,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 50,
            x: 210,
            y: 100,
            shape_type: 'v35',
            rotate: 0,
        },
    ],
}
