import { RoomLayout } from '../../types/room-layout'

export const mazeRoom: RoomLayout = {
    floor_image: '',
    font_size_ratio: 0.018,
    room_shape: {
        width: 330,
        height: 230,
    },
    seat_shape: {
        width: 35,
        height: 25,
    },
    partition_shapes: [
        {
            name: 'v25',
            width: 5,
            height: 25,
        },
        {
            name: 'v60',
            width: 5,
            height: 60,
        },
        {
            name: 'v65',
            width: 5,
            height: 65,
        },
        {
            name: 'v95',
            width: 5,
            height: 95,
        },
        {
            name: 'v75',
            width: 5,
            height: 75,
        },
        {
            name: 'v35',
            width: 5,
            height: 35,
        },
        {
            name: 'v30',
            width: 5,
            height: 30,
        },
        {
            name: 'v50',
            width: 5,
            height: 50,
        },
        {
            name: 'v45',
            width: 5,
            height: 45,
        },
        {
            name: 'v40',
            width: 5,
            height: 40,
        },
        {
            name: 'v80',
            width: 5,
            height: 80,
        },
        {
            name: 'h40',
            width: 40,
            height: 5,
        },
        {
            name: 'h100',
            width: 100,
            height: 5,
        },
        {
            name: 'h95',
            width: 95,
            height: 5,
        },
        {
            name: 'h35',
            width: 35,
            height: 5,
        },
        {
            name: 'h10',
            width: 10,
            height: 5,
        },
        {
            name: 'h55',
            width: 55,
            height: 5,
        },
        {
            name: 'h50',
            width: 50,
            height: 5,
        },
        {
            name: 'h20',
            width: 20,
            height: 5,
        },
        {
            name: 'h25',
            width: 25,
            height: 5,
        },
    ],
    seats: [
        {
            id: 1,
            x: 0,
            y: 0,
            rotate: 0,
        },
        {
            id: 2,
            x: 40,
            y: 0,
            rotate: 0,
        },
        {
            id: 3,
            x: 0,
            y: 45,
            rotate: 0,
        },
        {
            id: 4,
            x: 0,
            y: 75,
            rotate: 0,
        },
        {
            id: 5,
            x: 55,
            y: 45,
            rotate: 0,
        },
        {
            id: 6,
            x: 55,
            y: 75,
            rotate: 0,
        },
        {
            id: 7,
            x: 110,
            y: 20,
            rotate: 0,
        },
        {
            id: 8,
            x: 110,
            y: 50,
            rotate: 0,
        },
        {
            id: 9,
            x: 20,
            y: 125,
            rotate: 0,
        },
        {
            id: 10,
            x: 20,
            y: 155,
            rotate: 0,
        },
        {
            id: 11,
            x: 80,
            y: 125,
            rotate: 0,
        },
        {
            id: 12,
            x: 80,
            y: 155,
            rotate: 0,
        },
        {
            id: 13,
            x: 0,
            y: 205,
            rotate: 0,
        },
        {
            id: 14,
            x: 40,
            y: 205,
            rotate: 0,
        },
        {
            id: 15,
            x: 80,
            y: 205,
            rotate: 0,
        },
        {
            id: 16,
            x: 120,
            y: 95,
            rotate: 0,
        },
        {
            id: 17,
            x: 140,
            y: 145,
            rotate: 0,
        },
        {
            id: 18,
            x: 140,
            y: 190,
            rotate: 0,
        },
        {
            id: 19,
            x: 150,
            y: 0,
            rotate: 0,
        },
        {
            id: 20,
            x: 150,
            y: 30,
            rotate: 0,
        },
        {
            id: 21,
            x: 210,
            y: 0,
            rotate: 0,
        },
        {
            id: 22,
            x: 210,
            y: 30,
            rotate: 0,
        },
        {
            id: 23,
            x: 180,
            y: 80,
            rotate: 0,
        },
        {
            id: 24,
            x: 195,
            y: 130,
            rotate: 0,
        },
        {
            id: 25,
            x: 195,
            y: 190,
            rotate: 0,
        },
        {
            id: 26,
            x: 250,
            y: 0,
            rotate: 0,
        },
        {
            id: 27,
            x: 290,
            y: 0,
            rotate: 0,
        },
        {
            id: 28,
            x: 255,
            y: 40,
            rotate: 0,
        },
        {
            id: 29,
            x: 295,
            y: 55,
            rotate: 0,
        },
        {
            id: 30,
            x: 255,
            y: 70,
            rotate: 0,
        },
        {
            id: 31,
            x: 295,
            y: 85,
            rotate: 0,
        },
        {
            id: 32,
            x: 235,
            y: 115,
            rotate: 0,
        },
        {
            id: 33,
            x: 275,
            y: 130,
            rotate: 0,
        },
        {
            id: 34,
            x: 235,
            y: 145,
            rotate: 0,
        },
        {
            id: 35,
            x: 275,
            y: 160,
            rotate: 0,
        },
        {
            id: 36,
            x: 255,
            y: 205,
            rotate: 0,
        },
        {
            id: 37,
            x: 295,
            y: 205,
            rotate: 0,
        },
    ],
    partitions: [
        {
            id: 1,
            x: 35,
            y: 0,
            shape_type: 'v25',
            rotate: 0,
        },
        {
            id: 2,
            x: 75,
            y: 0,
            shape_type: 'v25',
            rotate: 0,
        },
        {
            id: 3,
            x: 0,
            y: 40,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 4,
            x: 0,
            y: 70,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 5,
            x: 50,
            y: 40,
            shape_type: 'v60',
            rotate: 0,
        },
        {
            id: 6,
            x: 55,
            y: 40,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 7,
            x: 55,
            y: 70,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 8,
            x: 0,
            y: 100,
            shape_type: 'h100',
            rotate: 0,
        },
        {
            id: 9,
            x: 95,
            y: 15,
            shape_type: 'h10',
            rotate: 0,
        },
        {
            id: 10,
            x: 105,
            y: 15,
            shape_type: 'v65',
            rotate: 0,
        },
        {
            id: 11,
            x: 110,
            y: 45,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 12,
            x: 15,
            y: 120,
            shape_type: 'v65',
            rotate: 0,
        },
        {
            id: 13,
            x: 20,
            y: 120,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 14,
            x: 20,
            y: 150,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 15,
            x: 75,
            y: 120,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 16,
            x: 75,
            y: 150,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 17,
            x: 20,
            y: 180,
            shape_type: 'h95',
            rotate: 0,
        },
        {
            id: 18,
            x: 35,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 19,
            x: 75,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 20,
            x: 115,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 21,
            x: 115,
            y: 90,
            shape_type: 'v95',
            rotate: 0,
        },
        {
            id: 22,
            x: 120,
            y: 90,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 23,
            x: 155,
            y: 90,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 24,
            x: 135,
            y: 140,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 25,
            x: 175,
            y: 140,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 26,
            x: 135,
            y: 170,
            shape_type: 'v50',
            rotate: 0,
        },
        {
            id: 27,
            x: 140,
            y: 170,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 28,
            x: 140,
            y: 215,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 29,
            x: 175,
            y: 125,
            shape_type: 'h55',
            rotate: 0,
        },
        {
            id: 30,
            x: 180,
            y: 170,
            shape_type: 'h50',
            rotate: 0,
        },
        {
            id: 31,
            x: 190,
            y: 175,
            shape_type: 'v45',
            rotate: 0,
        },
        {
            id: 32,
            x: 195,
            y: 215,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 33,
            x: 145,
            y: 0,
            shape_type: 'v75',
            rotate: 0,
        },
        {
            id: 34,
            x: 150,
            y: 25,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 35,
            x: 150,
            y: 70,
            shape_type: 'h25',
            rotate: 0,
        },
        {
            id: 36,
            x: 185,
            y: 30,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 37,
            x: 175,
            y: 70,
            shape_type: 'v40',
            rotate: 0,
        },
        {
            id: 38,
            x: 180,
            y: 75,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 39,
            x: 205,
            y: 25,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 40,
            x: 210,
            y: 25,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 41,
            x: 245,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 42,
            x: 285,
            y: 0,
            shape_type: 'v25',
            rotate: 0,
        },
        {
            id: 43,
            x: 210,
            y: 55,
            shape_type: 'h20',
            rotate: 0,
        },
        {
            id: 44,
            x: 230,
            y: 55,
            shape_type: 'v40',
            rotate: 0,
        },
        {
            id: 45,
            x: 250,
            y: 65,
            shape_type: 'v35',
            rotate: 0,
        },
        {
            id: 46,
            x: 255,
            y: 65,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 47,
            x: 290,
            y: 40,
            shape_type: 'v75',
            rotate: 0,
        },
        {
            id: 48,
            x: 295,
            y: 80,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 49,
            x: 230,
            y: 110,
            shape_type: 'v65',
            rotate: 0,
        },
        {
            id: 50,
            x: 235,
            y: 140,
            shape_type: 'h35',
            rotate: 0,
        },
        {
            id: 51,
            x: 270,
            y: 110,
            shape_type: 'v80',
            rotate: 0,
        },
        {
            id: 52,
            x: 275,
            y: 125,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 53,
            x: 275,
            y: 155,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 54,
            x: 275,
            y: 185,
            shape_type: 'h40',
            rotate: 0,
        },
        {
            id: 55,
            x: 250,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 56,
            x: 290,
            y: 200,
            shape_type: 'v30',
            rotate: 0,
        },
        {
            id: 57,
            x: 325,
            y: 0,
            shape_type: 'v30',
            rotate: 0,
        },
    ],
}
