import { RoomLayout } from '../../types/room-layout'

export const MemberSimpleRoom1: RoomLayout = {
    version: 1,
    floor_image: '/images/member_simple_room1.png',
    font_size_ratio: 0.015,
    room_shape: {
        width: 1520,
        height: 1000,
    },
    seat_shape: {
        width: 230,
        height: 130,
    },
    partition_shapes: [],
    seats: [
        {
            id: 1,
            x: 0,
            y: 0,
            rotate: 0,
        },
        {
            id: 2,
            x: 0,
            y: 150,
            rotate: 0,
        },
        {
            id: 3,
            x: 0,
            y: 300,
            rotate: 0,
        },
        {
            id: 4,
            x: 540,
            y: 0,
            rotate: 0,
        },
        {
            id: 5,
            x: 790,
            y: 0,
            rotate: 0,
        },
        {
            id: 6,
            x: 460,
            y: 250,
            rotate: 0,
        },
        {
            id: 7,
            x: 80,
            y: 570,
            rotate: 0,
        },
        {
            id: 8,
            x: 80,
            y: 720,
            rotate: 0,
        },
        {
            id: 9,
            x: 80,
            y: 870,
            rotate: 0,
        },
        {
            id: 10,
            x: 330,
            y: 570,
            rotate: 0,
        },
        {
            id: 11,
            x: 330,
            y: 720,
            rotate: 0,
        },
        {
            id: 12,
            x: 330,
            y: 870,
            rotate: 0,
        },
        {
            id: 13,
            x: 710,
            y: 400,
            rotate: 0,
        },
        {
            id: 14,
            x: 710,
            y: 700,
            rotate: 0,
        },
        {
            id: 15,
            x: 710,
            y: 850,
            rotate: 0,
        },
        {
            id: 16,
            x: 1040,
            y: 0,
            rotate: 0,
        },
        {
            id: 17,
            x: 1290,
            y: 0,
            rotate: 0,
        },
        {
            id: 18,
            x: 710,
            y: 250,
            rotate: 0,
        },
        {
            id: 19,
            x: 960,
            y: 400,
            rotate: 0,
        },
        {
            id: 20,
            x: 1210,
            y: 400,
            rotate: 0,
        },
        {
            id: 21,
            x: 710,
            y: 550,
            rotate: 0,
        },
        {
            id: 22,
            x: 960,
            y: 780,
            rotate: 0,
        },
        {
            id: 23,
            x: 1210,
            y: 780,
            rotate: 0,
        },
    ],
    partitions: [],
}
