import { RoomLayout } from '../../types/room-layout'

export const SeaOfSeatRoomLayout: RoomLayout = {
    floor_image: '',
    font_size_ratio: 0.02,
    room_shape: {
        width: 355,
        height: 240,
    },
    seat_shape: {
        width: 40,
        height: 30,
    },
    partition_shapes: [
        {
            name: 'l-v',
            width: 5,
            height: 240,
        },
    ],
    seats: [
        {
            id: 1,
            x: 0,
            y: 0,
            rotate: 0,
        },
        {
            id: 2,
            x: 0,
            y: 40,
            rotate: 0,
        },
        {
            id: 3,
            x: 0,
            y: 80,
            rotate: 0,
        },
        {
            id: 4,
            x: 0,
            y: 120,
            rotate: 0,
        },
        {
            id: 5,
            x: 0,
            y: 160,
            rotate: 0,
        },
        {
            id: 6,
            x: 0,
            y: 200,
            rotate: 0,
        },
        {
            id: 7,
            x: 45,
            y: 10,
            rotate: 0,
        },
        {
            id: 8,
            x: 45,
            y: 50,
            rotate: 0,
        },
        {
            id: 9,
            x: 45,
            y: 90,
            rotate: 0,
        },
        {
            id: 10,
            x: 45,
            y: 130,
            rotate: 0,
        },
        {
            id: 11,
            x: 45,
            y: 170,
            rotate: 0,
        },
        {
            id: 12,
            x: 45,
            y: 210,
            rotate: 0,
        },
        {
            id: 13,
            x: 90,
            y: 0,
            rotate: 0,
        },
        {
            id: 14,
            x: 90,
            y: 40,
            rotate: 0,
        },
        {
            id: 15,
            x: 90,
            y: 80,
            rotate: 0,
        },
        {
            id: 16,
            x: 90,
            y: 120,
            rotate: 0,
        },
        {
            id: 17,
            x: 90,
            y: 160,
            rotate: 0,
        },
        {
            id: 18,
            x: 90,
            y: 200,
            rotate: 0,
        },
        {
            id: 19,
            x: 135,
            y: 10,
            rotate: 0,
        },
        {
            id: 20,
            x: 135,
            y: 50,
            rotate: 0,
        },
        {
            id: 21,
            x: 135,
            y: 90,
            rotate: 0,
        },
        {
            id: 22,
            x: 135,
            y: 130,
            rotate: 0,
        },
        {
            id: 23,
            x: 135,
            y: 170,
            rotate: 0,
        },
        {
            id: 24,
            x: 135,
            y: 210,
            rotate: 0,
        },
        {
            id: 25,
            x: 180,
            y: 0,
            rotate: 0,
        },
        {
            id: 26,
            x: 180,
            y: 40,
            rotate: 0,
        },
        {
            id: 27,
            x: 180,
            y: 80,
            rotate: 0,
        },
        {
            id: 28,
            x: 180,
            y: 120,
            rotate: 0,
        },
        {
            id: 29,
            x: 180,
            y: 160,
            rotate: 0,
        },
        {
            id: 30,
            x: 180,
            y: 200,
            rotate: 0,
        },
        {
            id: 31,
            x: 225,
            y: 10,
            rotate: 0,
        },
        {
            id: 32,
            x: 225,
            y: 50,
            rotate: 0,
        },
        {
            id: 33,
            x: 225,
            y: 90,
            rotate: 0,
        },
        {
            id: 34,
            x: 225,
            y: 130,
            rotate: 0,
        },
        {
            id: 35,
            x: 225,
            y: 170,
            rotate: 0,
        },
        {
            id: 36,
            x: 225,
            y: 210,
            rotate: 0,
        },
        {
            id: 37,
            x: 270,
            y: 0,
            rotate: 0,
        },
        {
            id: 38,
            x: 270,
            y: 40,
            rotate: 0,
        },
        {
            id: 39,
            x: 270,
            y: 80,
            rotate: 0,
        },
        {
            id: 40,
            x: 270,
            y: 120,
            rotate: 0,
        },
        {
            id: 41,
            x: 270,
            y: 160,
            rotate: 0,
        },
        {
            id: 42,
            x: 270,
            y: 200,
            rotate: 0,
        },
        {
            id: 43,
            x: 315,
            y: 10,
            rotate: 0,
        },
        {
            id: 44,
            x: 315,
            y: 50,
            rotate: 0,
        },
        {
            id: 45,
            x: 315,
            y: 90,
            rotate: 0,
        },
        {
            id: 46,
            x: 315,
            y: 130,
            rotate: 0,
        },
        {
            id: 47,
            x: 315,
            y: 170,
            rotate: 0,
        },
        {
            id: 48,
            x: 315,
            y: 210,
            rotate: 0,
        },
    ],
    partitions: [
        {
            id: 1,
            x: 40,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 2,
            x: 85,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 3,
            x: 130,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 4,
            x: 175,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 5,
            x: 220,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 6,
            x: 265,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
        {
            id: 7,
            x: 310,
            y: 0,
            shape_type: 'l-v',
            rotate: 0,
        },
    ],
}
