blank_issues_enabled: true
contact_links:
  - name: コマンド一覧
    url: https://kani3camp.github.io/youtube-study-space/docs/essential
    about: コマンドの使い方に関する質問を投稿する前に、利用可能なコマンドと入力例を確認できます。
  - name: Discordコミュニティ
    url: https://discord.gg/h9SenAvawT
    about: 一般的な使い方の質問や、利用者同士の交流はこちらから行えます。
