FROM golang:1.26@sha256:3aff6657219a4d9c14e27fb1d8976c49c29fddb70ba835014f477e1c70636647 AS build
WORKDIR /src

# 依存関係キャッシュを効かせるために先に go.mod/go.sum だけコピー
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

# アプリコードをコピー
COPY . .

# Build for linux/${GOARCH}, static, no cgo
ARG GOARCH=arm64
ARG BUILD_TARGET=./cmd/batch
ENV CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target=/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go build -tags timetzdata -trimpath -ldflags="-s -w" -o /out/batch ${BUILD_TARGET}

FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
WORKDIR /app
ENV TZ=Asia/Tokyo
COPY --from=build /out/batch /app/batch
USER nonroot:nonroot
ENTRYPOINT ["/app/batch"]
