FROM golang:1.26@sha256:5f3787b7f902c07c7ec4f3aa91a301a3eda8133aa32661a3b3a3a86ab3a68a36 AS build
WORKDIR /src

# 依存関係キャッシュを効かせるために先に go.mod/go.sum だけコピー
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

# アプリコードをコピー
COPY . .

# Build for linux/${GOARCH}, static, no cgo
ARG GOARCH=arm64
ARG BUILD_TARGET=./cmd/batch
ENV CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target=/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  go build -tags timetzdata -trimpath -ldflags="-s -w" -o /out/batch ${BUILD_TARGET}

FROM gcr.io/distroless/static-debian12:nonroot@sha256:a9329520abc449e3b14d5bc3a6ffae065bdde0f02667fa10880c49b35c109fd1
WORKDIR /app
ENV TZ=Asia/Tokyo
COPY --from=build /out/batch /app/batch
USER nonroot:nonroot
ENTRYPOINT ["/app/batch"]

