// Code generated by MockGen. DO NOT EDIT.
// Source: firestore_controller_interface.go
//
// Generated by this command:
//
//	mockgen -source=firestore_controller_interface.go -destination=mocks/firestore_controller_interface.go
//

// Package mock_myfirestore is a generated GoMock package.
package mock_myfirestore

import (
	context "context"
	reflect "reflect"
	time "time"

	myfirestore "app.modules/core/myfirestore"
	firestore "cloud.google.com/go/firestore"
	gomock "go.uber.org/mock/gomock"
)

// MockFirestoreClient is a mock of FirestoreClient interface.
type MockFirestoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirestoreClientMockRecorder
	isgomock struct{}
}

// MockFirestoreClientMockRecorder is the mock recorder for MockFirestoreClient.
type MockFirestoreClientMockRecorder struct {
	mock *MockFirestoreClient
}

// NewMockFirestoreClient creates a new mock instance.
func NewMockFirestoreClient(ctrl *gomock.Controller) *MockFirestoreClient {
	mock := &MockFirestoreClient{ctrl: ctrl}
	mock.recorder = &MockFirestoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirestoreClient) EXPECT() *MockFirestoreClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFirestoreClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFirestoreClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFirestoreClient)(nil).Close))
}

// Collection mocks base method.
func (m *MockFirestoreClient) Collection(path string) *firestore.CollectionRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection", path)
	ret0, _ := ret[0].(*firestore.CollectionRef)
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockFirestoreClientMockRecorder) Collection(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockFirestoreClient)(nil).Collection), path)
}

// Doc mocks base method.
func (m *MockFirestoreClient) Doc(path string) *firestore.DocumentRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Doc", path)
	ret0, _ := ret[0].(*firestore.DocumentRef)
	return ret0
}

// Doc indicates an expected call of Doc.
func (mr *MockFirestoreClientMockRecorder) Doc(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Doc", reflect.TypeOf((*MockFirestoreClient)(nil).Doc), path)
}

// RunTransaction mocks base method.
func (m *MockFirestoreClient) RunTransaction(ctx context.Context, f func(context.Context, *firestore.Transaction) error, opts ...firestore.TransactionOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockFirestoreClientMockRecorder) RunTransaction(ctx, f any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockFirestoreClient)(nil).RunTransaction), varargs...)
}

// MockFirestoreController is a mock of FirestoreController interface.
type MockFirestoreController struct {
	ctrl     *gomock.Controller
	recorder *MockFirestoreControllerMockRecorder
	isgomock struct{}
}

// MockFirestoreControllerMockRecorder is the mock recorder for MockFirestoreController.
type MockFirestoreControllerMockRecorder struct {
	mock *MockFirestoreController
}

// NewMockFirestoreController creates a new mock instance.
func NewMockFirestoreController(ctrl *gomock.Controller) *MockFirestoreController {
	mock := &MockFirestoreController{ctrl: ctrl}
	mock.recorder = &MockFirestoreControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirestoreController) EXPECT() *MockFirestoreControllerMockRecorder {
	return m.recorder
}

// CreateLiveChatHistoryDoc mocks base method.
func (m *MockFirestoreController) CreateLiveChatHistoryDoc(ctx context.Context, tx *firestore.Transaction, liveChatHistoryDoc myfirestore.LiveChatHistoryDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLiveChatHistoryDoc", ctx, tx, liveChatHistoryDoc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLiveChatHistoryDoc indicates an expected call of CreateLiveChatHistoryDoc.
func (mr *MockFirestoreControllerMockRecorder) CreateLiveChatHistoryDoc(ctx, tx, liveChatHistoryDoc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLiveChatHistoryDoc", reflect.TypeOf((*MockFirestoreController)(nil).CreateLiveChatHistoryDoc), ctx, tx, liveChatHistoryDoc)
}

// CreateSeat mocks base method.
func (m *MockFirestoreController) CreateSeat(tx *firestore.Transaction, seat myfirestore.SeatDoc, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeat", tx, seat, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeat indicates an expected call of CreateSeat.
func (mr *MockFirestoreControllerMockRecorder) CreateSeat(tx, seat, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeat", reflect.TypeOf((*MockFirestoreController)(nil).CreateSeat), tx, seat, isMemberSeat)
}

// CreateSeatLimitInBLACKList mocks base method.
func (m *MockFirestoreController) CreateSeatLimitInBLACKList(ctx context.Context, seatId int, userId string, createdAt, until time.Time, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeatLimitInBLACKList", ctx, seatId, userId, createdAt, until, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeatLimitInBLACKList indicates an expected call of CreateSeatLimitInBLACKList.
func (mr *MockFirestoreControllerMockRecorder) CreateSeatLimitInBLACKList(ctx, seatId, userId, createdAt, until, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeatLimitInBLACKList", reflect.TypeOf((*MockFirestoreController)(nil).CreateSeatLimitInBLACKList), ctx, seatId, userId, createdAt, until, isMemberSeat)
}

// CreateSeatLimitInWHITEList mocks base method.
func (m *MockFirestoreController) CreateSeatLimitInWHITEList(ctx context.Context, seatId int, userId string, createdAt, until time.Time, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeatLimitInWHITEList", ctx, seatId, userId, createdAt, until, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSeatLimitInWHITEList indicates an expected call of CreateSeatLimitInWHITEList.
func (mr *MockFirestoreControllerMockRecorder) CreateSeatLimitInWHITEList(ctx, seatId, userId, createdAt, until, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeatLimitInWHITEList", reflect.TypeOf((*MockFirestoreController)(nil).CreateSeatLimitInWHITEList), ctx, seatId, userId, createdAt, until, isMemberSeat)
}

// CreateUser mocks base method.
func (m *MockFirestoreController) CreateUser(ctx context.Context, tx *firestore.Transaction, userId string, userData myfirestore.UserDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, tx, userId, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockFirestoreControllerMockRecorder) CreateUser(ctx, tx, userId, userData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockFirestoreController)(nil).CreateUser), ctx, tx, userId, userData)
}

// CreateUserActivityDoc mocks base method.
func (m *MockFirestoreController) CreateUserActivityDoc(ctx context.Context, tx *firestore.Transaction, activity myfirestore.UserActivityDoc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserActivityDoc", ctx, tx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserActivityDoc indicates an expected call of CreateUserActivityDoc.
func (mr *MockFirestoreControllerMockRecorder) CreateUserActivityDoc(ctx, tx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserActivityDoc", reflect.TypeOf((*MockFirestoreController)(nil).CreateUserActivityDoc), ctx, tx, activity)
}

// DeleteDocRef mocks base method.
func (m *MockFirestoreController) DeleteDocRef(ctx context.Context, tx *firestore.Transaction, ref *firestore.DocumentRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDocRef", ctx, tx, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDocRef indicates an expected call of DeleteDocRef.
func (mr *MockFirestoreControllerMockRecorder) DeleteDocRef(ctx, tx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDocRef", reflect.TypeOf((*MockFirestoreController)(nil).DeleteDocRef), ctx, tx, ref)
}

// DeleteSeat mocks base method.
func (m *MockFirestoreController) DeleteSeat(ctx context.Context, tx *firestore.Transaction, seatId int, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeat", ctx, tx, seatId, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeat indicates an expected call of DeleteSeat.
func (mr *MockFirestoreControllerMockRecorder) DeleteSeat(ctx, tx, seatId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeat", reflect.TypeOf((*MockFirestoreController)(nil).DeleteSeat), ctx, tx, seatId, isMemberSeat)
}

// DeleteSeatLimitInBLACKList mocks base method.
func (m *MockFirestoreController) DeleteSeatLimitInBLACKList(ctx context.Context, docId string, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeatLimitInBLACKList", ctx, docId, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeatLimitInBLACKList indicates an expected call of DeleteSeatLimitInBLACKList.
func (mr *MockFirestoreControllerMockRecorder) DeleteSeatLimitInBLACKList(ctx, docId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeatLimitInBLACKList", reflect.TypeOf((*MockFirestoreController)(nil).DeleteSeatLimitInBLACKList), ctx, docId, isMemberSeat)
}

// DeleteSeatLimitInWHITEList mocks base method.
func (m *MockFirestoreController) DeleteSeatLimitInWHITEList(ctx context.Context, docId string, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeatLimitInWHITEList", ctx, docId, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeatLimitInWHITEList indicates an expected call of DeleteSeatLimitInWHITEList.
func (mr *MockFirestoreControllerMockRecorder) DeleteSeatLimitInWHITEList(ctx, docId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeatLimitInWHITEList", reflect.TypeOf((*MockFirestoreController)(nil).DeleteSeatLimitInWHITEList), ctx, docId, isMemberSeat)
}

// FirestoreClient mocks base method.
func (m *MockFirestoreController) FirestoreClient() myfirestore.FirestoreClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirestoreClient")
	ret0, _ := ret[0].(myfirestore.FirestoreClient)
	return ret0
}

// FirestoreClient indicates an expected call of FirestoreClient.
func (mr *MockFirestoreControllerMockRecorder) FirestoreClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirestoreClient", reflect.TypeOf((*MockFirestoreController)(nil).FirestoreClient))
}

// Get500LiveChatHistoryDocIdsBeforeDate mocks base method.
func (m *MockFirestoreController) Get500LiveChatHistoryDocIdsBeforeDate(ctx context.Context, date time.Time) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get500LiveChatHistoryDocIdsBeforeDate", ctx, date)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// Get500LiveChatHistoryDocIdsBeforeDate indicates an expected call of Get500LiveChatHistoryDocIdsBeforeDate.
func (mr *MockFirestoreControllerMockRecorder) Get500LiveChatHistoryDocIdsBeforeDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get500LiveChatHistoryDocIdsBeforeDate", reflect.TypeOf((*MockFirestoreController)(nil).Get500LiveChatHistoryDocIdsBeforeDate), ctx, date)
}

// Get500SeatLimitsAfterUntilInBLACKList mocks base method.
func (m *MockFirestoreController) Get500SeatLimitsAfterUntilInBLACKList(ctx context.Context, thresholdTime time.Time, isMemberSeat bool) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get500SeatLimitsAfterUntilInBLACKList", ctx, thresholdTime, isMemberSeat)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// Get500SeatLimitsAfterUntilInBLACKList indicates an expected call of Get500SeatLimitsAfterUntilInBLACKList.
func (mr *MockFirestoreControllerMockRecorder) Get500SeatLimitsAfterUntilInBLACKList(ctx, thresholdTime, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get500SeatLimitsAfterUntilInBLACKList", reflect.TypeOf((*MockFirestoreController)(nil).Get500SeatLimitsAfterUntilInBLACKList), ctx, thresholdTime, isMemberSeat)
}

// Get500SeatLimitsAfterUntilInWHITEList mocks base method.
func (m *MockFirestoreController) Get500SeatLimitsAfterUntilInWHITEList(ctx context.Context, thresholdTime time.Time, isMemberSeat bool) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get500SeatLimitsAfterUntilInWHITEList", ctx, thresholdTime, isMemberSeat)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// Get500SeatLimitsAfterUntilInWHITEList indicates an expected call of Get500SeatLimitsAfterUntilInWHITEList.
func (mr *MockFirestoreControllerMockRecorder) Get500SeatLimitsAfterUntilInWHITEList(ctx, thresholdTime, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get500SeatLimitsAfterUntilInWHITEList", reflect.TypeOf((*MockFirestoreController)(nil).Get500SeatLimitsAfterUntilInWHITEList), ctx, thresholdTime, isMemberSeat)
}

// Get500UserActivityDocIdsBeforeDate mocks base method.
func (m *MockFirestoreController) Get500UserActivityDocIdsBeforeDate(ctx context.Context, date time.Time) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get500UserActivityDocIdsBeforeDate", ctx, date)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// Get500UserActivityDocIdsBeforeDate indicates an expected call of Get500UserActivityDocIdsBeforeDate.
func (mr *MockFirestoreControllerMockRecorder) Get500UserActivityDocIdsBeforeDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get500UserActivityDocIdsBeforeDate", reflect.TypeOf((*MockFirestoreController)(nil).Get500UserActivityDocIdsBeforeDate), ctx, date)
}

// GetAllNonDailyZeroUserDocs mocks base method.
func (m *MockFirestoreController) GetAllNonDailyZeroUserDocs(ctx context.Context) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNonDailyZeroUserDocs", ctx)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// GetAllNonDailyZeroUserDocs indicates an expected call of GetAllNonDailyZeroUserDocs.
func (mr *MockFirestoreControllerMockRecorder) GetAllNonDailyZeroUserDocs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNonDailyZeroUserDocs", reflect.TypeOf((*MockFirestoreController)(nil).GetAllNonDailyZeroUserDocs), ctx)
}

// GetAllUserActivityDocIdsAfterDate mocks base method.
func (m *MockFirestoreController) GetAllUserActivityDocIdsAfterDate(ctx context.Context, date time.Time) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserActivityDocIdsAfterDate", ctx, date)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// GetAllUserActivityDocIdsAfterDate indicates an expected call of GetAllUserActivityDocIdsAfterDate.
func (mr *MockFirestoreControllerMockRecorder) GetAllUserActivityDocIdsAfterDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserActivityDocIdsAfterDate", reflect.TypeOf((*MockFirestoreController)(nil).GetAllUserActivityDocIdsAfterDate), ctx, date)
}

// GetAllUserDocRefs mocks base method.
func (m *MockFirestoreController) GetAllUserDocRefs(ctx context.Context) ([]*firestore.DocumentRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserDocRefs", ctx)
	ret0, _ := ret[0].([]*firestore.DocumentRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserDocRefs indicates an expected call of GetAllUserDocRefs.
func (mr *MockFirestoreControllerMockRecorder) GetAllUserDocRefs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserDocRefs", reflect.TypeOf((*MockFirestoreController)(nil).GetAllUserDocRefs), ctx)
}

// GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat mocks base method.
func (m *MockFirestoreController) GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat(ctx context.Context, date time.Time, userId string, seatId int, isMemberSeat bool) ([]myfirestore.UserActivityDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat", ctx, date, userId, seatId, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.UserActivityDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat indicates an expected call of GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat.
func (mr *MockFirestoreControllerMockRecorder) GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat(ctx, date, userId, seatId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat", reflect.TypeOf((*MockFirestoreController)(nil).GetEnterRoomUserActivityDocIdsAfterDateForUserAndSeat), ctx, date, userId, seatId, isMemberSeat)
}

// GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat mocks base method.
func (m *MockFirestoreController) GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat(ctx context.Context, date time.Time, userId string, seatId int, isMemberSeat bool) ([]myfirestore.UserActivityDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat", ctx, date, userId, seatId, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.UserActivityDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat indicates an expected call of GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat.
func (mr *MockFirestoreControllerMockRecorder) GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat(ctx, date, userId, seatId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat", reflect.TypeOf((*MockFirestoreController)(nil).GetExitRoomUserActivityDocIdsAfterDateForUserAndSeat), ctx, date, userId, seatId, isMemberSeat)
}

// GetUsersActiveAfterDate mocks base method.
func (m *MockFirestoreController) GetUsersActiveAfterDate(ctx context.Context, date time.Time) *firestore.DocumentIterator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersActiveAfterDate", ctx, date)
	ret0, _ := ret[0].(*firestore.DocumentIterator)
	return ret0
}

// GetUsersActiveAfterDate indicates an expected call of GetUsersActiveAfterDate.
func (mr *MockFirestoreControllerMockRecorder) GetUsersActiveAfterDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersActiveAfterDate", reflect.TypeOf((*MockFirestoreController)(nil).GetUsersActiveAfterDate), ctx, date)
}

// ReadCredentialsConfig mocks base method.
func (m *MockFirestoreController) ReadCredentialsConfig(ctx context.Context, tx *firestore.Transaction) (myfirestore.CredentialsConfigDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCredentialsConfig", ctx, tx)
	ret0, _ := ret[0].(myfirestore.CredentialsConfigDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCredentialsConfig indicates an expected call of ReadCredentialsConfig.
func (mr *MockFirestoreControllerMockRecorder) ReadCredentialsConfig(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCredentialsConfig", reflect.TypeOf((*MockFirestoreController)(nil).ReadCredentialsConfig), ctx, tx)
}

// ReadGeneralSeats mocks base method.
func (m *MockFirestoreController) ReadGeneralSeats(ctx context.Context) ([]myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadGeneralSeats", ctx)
	ret0, _ := ret[0].([]myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadGeneralSeats indicates an expected call of ReadGeneralSeats.
func (mr *MockFirestoreControllerMockRecorder) ReadGeneralSeats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadGeneralSeats", reflect.TypeOf((*MockFirestoreController)(nil).ReadGeneralSeats), ctx)
}

// ReadLiveChatId mocks base method.
func (m *MockFirestoreController) ReadLiveChatId(ctx context.Context, tx *firestore.Transaction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLiveChatId", ctx, tx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLiveChatId indicates an expected call of ReadLiveChatId.
func (mr *MockFirestoreControllerMockRecorder) ReadLiveChatId(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLiveChatId", reflect.TypeOf((*MockFirestoreController)(nil).ReadLiveChatId), ctx, tx)
}

// ReadMemberSeats mocks base method.
func (m *MockFirestoreController) ReadMemberSeats(ctx context.Context) ([]myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMemberSeats", ctx)
	ret0, _ := ret[0].([]myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMemberSeats indicates an expected call of ReadMemberSeats.
func (mr *MockFirestoreControllerMockRecorder) ReadMemberSeats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMemberSeats", reflect.TypeOf((*MockFirestoreController)(nil).ReadMemberSeats), ctx)
}

// ReadNextPageToken mocks base method.
func (m *MockFirestoreController) ReadNextPageToken(ctx context.Context, tx *firestore.Transaction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadNextPageToken", ctx, tx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadNextPageToken indicates an expected call of ReadNextPageToken.
func (mr *MockFirestoreControllerMockRecorder) ReadNextPageToken(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadNextPageToken", reflect.TypeOf((*MockFirestoreController)(nil).ReadNextPageToken), ctx, tx)
}

// ReadSeat mocks base method.
func (m *MockFirestoreController) ReadSeat(ctx context.Context, tx *firestore.Transaction, seatId int, isMemberSeat bool) (myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeat", ctx, tx, seatId, isMemberSeat)
	ret0, _ := ret[0].(myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeat indicates an expected call of ReadSeat.
func (mr *MockFirestoreControllerMockRecorder) ReadSeat(ctx, tx, seatId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeat", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeat), ctx, tx, seatId, isMemberSeat)
}

// ReadSeatLimitsBLACKListWithSeatIdAndUserId mocks base method.
func (m *MockFirestoreController) ReadSeatLimitsBLACKListWithSeatIdAndUserId(ctx context.Context, seatId int, userId string, isMemberSeat bool) ([]myfirestore.SeatLimitDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeatLimitsBLACKListWithSeatIdAndUserId", ctx, seatId, userId, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.SeatLimitDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeatLimitsBLACKListWithSeatIdAndUserId indicates an expected call of ReadSeatLimitsBLACKListWithSeatIdAndUserId.
func (mr *MockFirestoreControllerMockRecorder) ReadSeatLimitsBLACKListWithSeatIdAndUserId(ctx, seatId, userId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeatLimitsBLACKListWithSeatIdAndUserId", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeatLimitsBLACKListWithSeatIdAndUserId), ctx, seatId, userId, isMemberSeat)
}

// ReadSeatLimitsWHITEListWithSeatIdAndUserId mocks base method.
func (m *MockFirestoreController) ReadSeatLimitsWHITEListWithSeatIdAndUserId(ctx context.Context, seatId int, userId string, isMemberSeat bool) ([]myfirestore.SeatLimitDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeatLimitsWHITEListWithSeatIdAndUserId", ctx, seatId, userId, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.SeatLimitDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeatLimitsWHITEListWithSeatIdAndUserId indicates an expected call of ReadSeatLimitsWHITEListWithSeatIdAndUserId.
func (mr *MockFirestoreControllerMockRecorder) ReadSeatLimitsWHITEListWithSeatIdAndUserId(ctx, seatId, userId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeatLimitsWHITEListWithSeatIdAndUserId", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeatLimitsWHITEListWithSeatIdAndUserId), ctx, seatId, userId, isMemberSeat)
}

// ReadSeatWithUserId mocks base method.
func (m *MockFirestoreController) ReadSeatWithUserId(ctx context.Context, userId string, isMemberSeat bool) (myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeatWithUserId", ctx, userId, isMemberSeat)
	ret0, _ := ret[0].(myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeatWithUserId indicates an expected call of ReadSeatWithUserId.
func (mr *MockFirestoreControllerMockRecorder) ReadSeatWithUserId(ctx, userId, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeatWithUserId", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeatWithUserId), ctx, userId, isMemberSeat)
}

// ReadSeatsExpiredBreakUntil mocks base method.
func (m *MockFirestoreController) ReadSeatsExpiredBreakUntil(ctx context.Context, thresholdTime time.Time, isMemberSeat bool) ([]myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeatsExpiredBreakUntil", ctx, thresholdTime, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeatsExpiredBreakUntil indicates an expected call of ReadSeatsExpiredBreakUntil.
func (mr *MockFirestoreControllerMockRecorder) ReadSeatsExpiredBreakUntil(ctx, thresholdTime, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeatsExpiredBreakUntil", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeatsExpiredBreakUntil), ctx, thresholdTime, isMemberSeat)
}

// ReadSeatsExpiredUntil mocks base method.
func (m *MockFirestoreController) ReadSeatsExpiredUntil(ctx context.Context, thresholdTime time.Time, isMemberSeat bool) ([]myfirestore.SeatDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSeatsExpiredUntil", ctx, thresholdTime, isMemberSeat)
	ret0, _ := ret[0].([]myfirestore.SeatDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSeatsExpiredUntil indicates an expected call of ReadSeatsExpiredUntil.
func (mr *MockFirestoreControllerMockRecorder) ReadSeatsExpiredUntil(ctx, thresholdTime, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSeatsExpiredUntil", reflect.TypeOf((*MockFirestoreController)(nil).ReadSeatsExpiredUntil), ctx, thresholdTime, isMemberSeat)
}

// ReadSystemConstantsConfig mocks base method.
func (m *MockFirestoreController) ReadSystemConstantsConfig(ctx context.Context, tx *firestore.Transaction) (myfirestore.ConstantsConfigDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSystemConstantsConfig", ctx, tx)
	ret0, _ := ret[0].(myfirestore.ConstantsConfigDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSystemConstantsConfig indicates an expected call of ReadSystemConstantsConfig.
func (mr *MockFirestoreControllerMockRecorder) ReadSystemConstantsConfig(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSystemConstantsConfig", reflect.TypeOf((*MockFirestoreController)(nil).ReadSystemConstantsConfig), ctx, tx)
}

// ReadUser mocks base method.
func (m *MockFirestoreController) ReadUser(ctx context.Context, tx *firestore.Transaction, userId string) (myfirestore.UserDoc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUser", ctx, tx, userId)
	ret0, _ := ret[0].(myfirestore.UserDoc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUser indicates an expected call of ReadUser.
func (mr *MockFirestoreControllerMockRecorder) ReadUser(ctx, tx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUser", reflect.TypeOf((*MockFirestoreController)(nil).ReadUser), ctx, tx, userId)
}

// ResetDailyTotalStudyTime mocks base method.
func (m *MockFirestoreController) ResetDailyTotalStudyTime(ctx context.Context, userRef *firestore.DocumentRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetDailyTotalStudyTime", ctx, userRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetDailyTotalStudyTime indicates an expected call of ResetDailyTotalStudyTime.
func (mr *MockFirestoreControllerMockRecorder) ResetDailyTotalStudyTime(ctx, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetDailyTotalStudyTime", reflect.TypeOf((*MockFirestoreController)(nil).ResetDailyTotalStudyTime), ctx, userRef)
}

// UpdateAccessTokenOfBotCredential mocks base method.
func (m *MockFirestoreController) UpdateAccessTokenOfBotCredential(ctx context.Context, tx *firestore.Transaction, accessToken string, expireDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessTokenOfBotCredential", ctx, tx, accessToken, expireDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessTokenOfBotCredential indicates an expected call of UpdateAccessTokenOfBotCredential.
func (mr *MockFirestoreControllerMockRecorder) UpdateAccessTokenOfBotCredential(ctx, tx, accessToken, expireDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessTokenOfBotCredential", reflect.TypeOf((*MockFirestoreController)(nil).UpdateAccessTokenOfBotCredential), ctx, tx, accessToken, expireDate)
}

// UpdateAccessTokenOfChannelCredential mocks base method.
func (m *MockFirestoreController) UpdateAccessTokenOfChannelCredential(ctx context.Context, tx *firestore.Transaction, accessToken string, expireDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessTokenOfChannelCredential", ctx, tx, accessToken, expireDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessTokenOfChannelCredential indicates an expected call of UpdateAccessTokenOfChannelCredential.
func (mr *MockFirestoreControllerMockRecorder) UpdateAccessTokenOfChannelCredential(ctx, tx, accessToken, expireDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessTokenOfChannelCredential", reflect.TypeOf((*MockFirestoreController)(nil).UpdateAccessTokenOfChannelCredential), ctx, tx, accessToken, expireDate)
}

// UpdateDesiredMaxSeats mocks base method.
func (m *MockFirestoreController) UpdateDesiredMaxSeats(ctx context.Context, tx *firestore.Transaction, desiredMaxSeats int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDesiredMaxSeats", ctx, tx, desiredMaxSeats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDesiredMaxSeats indicates an expected call of UpdateDesiredMaxSeats.
func (mr *MockFirestoreControllerMockRecorder) UpdateDesiredMaxSeats(ctx, tx, desiredMaxSeats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDesiredMaxSeats", reflect.TypeOf((*MockFirestoreController)(nil).UpdateDesiredMaxSeats), ctx, tx, desiredMaxSeats)
}

// UpdateDesiredMemberMaxSeats mocks base method.
func (m *MockFirestoreController) UpdateDesiredMemberMaxSeats(ctx context.Context, tx *firestore.Transaction, desiredMemberMaxSeats int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDesiredMemberMaxSeats", ctx, tx, desiredMemberMaxSeats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDesiredMemberMaxSeats indicates an expected call of UpdateDesiredMemberMaxSeats.
func (mr *MockFirestoreControllerMockRecorder) UpdateDesiredMemberMaxSeats(ctx, tx, desiredMemberMaxSeats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDesiredMemberMaxSeats", reflect.TypeOf((*MockFirestoreController)(nil).UpdateDesiredMemberMaxSeats), ctx, tx, desiredMemberMaxSeats)
}

// UpdateLastLongTimeSittingChecked mocks base method.
func (m *MockFirestoreController) UpdateLastLongTimeSittingChecked(ctx context.Context, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLongTimeSittingChecked", ctx, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLongTimeSittingChecked indicates an expected call of UpdateLastLongTimeSittingChecked.
func (mr *MockFirestoreControllerMockRecorder) UpdateLastLongTimeSittingChecked(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLongTimeSittingChecked", reflect.TypeOf((*MockFirestoreController)(nil).UpdateLastLongTimeSittingChecked), ctx, timestamp)
}

// UpdateLastResetDailyTotalStudyTime mocks base method.
func (m *MockFirestoreController) UpdateLastResetDailyTotalStudyTime(ctx context.Context, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastResetDailyTotalStudyTime", ctx, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastResetDailyTotalStudyTime indicates an expected call of UpdateLastResetDailyTotalStudyTime.
func (mr *MockFirestoreControllerMockRecorder) UpdateLastResetDailyTotalStudyTime(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastResetDailyTotalStudyTime", reflect.TypeOf((*MockFirestoreController)(nil).UpdateLastResetDailyTotalStudyTime), ctx, timestamp)
}

// UpdateLastTransferCollectionHistoryBigquery mocks base method.
func (m *MockFirestoreController) UpdateLastTransferCollectionHistoryBigquery(ctx context.Context, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastTransferCollectionHistoryBigquery", ctx, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastTransferCollectionHistoryBigquery indicates an expected call of UpdateLastTransferCollectionHistoryBigquery.
func (mr *MockFirestoreControllerMockRecorder) UpdateLastTransferCollectionHistoryBigquery(ctx, timestamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastTransferCollectionHistoryBigquery", reflect.TypeOf((*MockFirestoreController)(nil).UpdateLastTransferCollectionHistoryBigquery), ctx, timestamp)
}

// UpdateLiveChatId mocks base method.
func (m *MockFirestoreController) UpdateLiveChatId(ctx context.Context, tx *firestore.Transaction, liveChatId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLiveChatId", ctx, tx, liveChatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLiveChatId indicates an expected call of UpdateLiveChatId.
func (mr *MockFirestoreControllerMockRecorder) UpdateLiveChatId(ctx, tx, liveChatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLiveChatId", reflect.TypeOf((*MockFirestoreController)(nil).UpdateLiveChatId), ctx, tx, liveChatId)
}

// UpdateMaxSeats mocks base method.
func (m *MockFirestoreController) UpdateMaxSeats(ctx context.Context, tx *firestore.Transaction, maxSeats int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaxSeats", ctx, tx, maxSeats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaxSeats indicates an expected call of UpdateMaxSeats.
func (mr *MockFirestoreControllerMockRecorder) UpdateMaxSeats(ctx, tx, maxSeats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaxSeats", reflect.TypeOf((*MockFirestoreController)(nil).UpdateMaxSeats), ctx, tx, maxSeats)
}

// UpdateMemberMaxSeats mocks base method.
func (m *MockFirestoreController) UpdateMemberMaxSeats(ctx context.Context, tx *firestore.Transaction, memberMaxSeats int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberMaxSeats", ctx, tx, memberMaxSeats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberMaxSeats indicates an expected call of UpdateMemberMaxSeats.
func (mr *MockFirestoreControllerMockRecorder) UpdateMemberMaxSeats(ctx, tx, memberMaxSeats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberMaxSeats", reflect.TypeOf((*MockFirestoreController)(nil).UpdateMemberMaxSeats), ctx, tx, memberMaxSeats)
}

// UpdateNextPageToken mocks base method.
func (m *MockFirestoreController) UpdateNextPageToken(ctx context.Context, nextPageToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNextPageToken", ctx, nextPageToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNextPageToken indicates an expected call of UpdateNextPageToken.
func (mr *MockFirestoreControllerMockRecorder) UpdateNextPageToken(ctx, nextPageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNextPageToken", reflect.TypeOf((*MockFirestoreController)(nil).UpdateNextPageToken), ctx, nextPageToken)
}

// UpdateSeat mocks base method.
func (m *MockFirestoreController) UpdateSeat(ctx context.Context, tx *firestore.Transaction, seat myfirestore.SeatDoc, isMemberSeat bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeat", ctx, tx, seat, isMemberSeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSeat indicates an expected call of UpdateSeat.
func (mr *MockFirestoreControllerMockRecorder) UpdateSeat(ctx, tx, seat, isMemberSeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeat", reflect.TypeOf((*MockFirestoreController)(nil).UpdateSeat), ctx, tx, seat, isMemberSeat)
}

// UpdateUserDefaultStudyMin mocks base method.
func (m *MockFirestoreController) UpdateUserDefaultStudyMin(tx *firestore.Transaction, userId string, defaultStudyMin int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserDefaultStudyMin", tx, userId, defaultStudyMin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserDefaultStudyMin indicates an expected call of UpdateUserDefaultStudyMin.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserDefaultStudyMin(tx, userId, defaultStudyMin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserDefaultStudyMin", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserDefaultStudyMin), tx, userId, defaultStudyMin)
}

// UpdateUserFavoriteColor mocks base method.
func (m *MockFirestoreController) UpdateUserFavoriteColor(tx *firestore.Transaction, userId, colorCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserFavoriteColor", tx, userId, colorCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserFavoriteColor indicates an expected call of UpdateUserFavoriteColor.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserFavoriteColor(tx, userId, colorCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserFavoriteColor", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserFavoriteColor), tx, userId, colorCode)
}

// UpdateUserIsContinuousActiveAndCurrentActivityStateStarted mocks base method.
func (m *MockFirestoreController) UpdateUserIsContinuousActiveAndCurrentActivityStateStarted(ctx context.Context, tx *firestore.Transaction, userId string, isContinuousActive bool, currentActivityStateStarted time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserIsContinuousActiveAndCurrentActivityStateStarted", ctx, tx, userId, isContinuousActive, currentActivityStateStarted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserIsContinuousActiveAndCurrentActivityStateStarted indicates an expected call of UpdateUserIsContinuousActiveAndCurrentActivityStateStarted.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserIsContinuousActiveAndCurrentActivityStateStarted(ctx, tx, userId, isContinuousActive, currentActivityStateStarted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserIsContinuousActiveAndCurrentActivityStateStarted", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserIsContinuousActiveAndCurrentActivityStateStarted), ctx, tx, userId, isContinuousActive, currentActivityStateStarted)
}

// UpdateUserLastEnteredDate mocks base method.
func (m *MockFirestoreController) UpdateUserLastEnteredDate(tx *firestore.Transaction, userId string, enteredDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastEnteredDate", tx, userId, enteredDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastEnteredDate indicates an expected call of UpdateUserLastEnteredDate.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserLastEnteredDate(tx, userId, enteredDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastEnteredDate", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserLastEnteredDate), tx, userId, enteredDate)
}

// UpdateUserLastExitedDate mocks base method.
func (m *MockFirestoreController) UpdateUserLastExitedDate(tx *firestore.Transaction, userId string, exitedDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastExitedDate", tx, userId, exitedDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastExitedDate indicates an expected call of UpdateUserLastExitedDate.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserLastExitedDate(tx, userId, exitedDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastExitedDate", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserLastExitedDate), tx, userId, exitedDate)
}

// UpdateUserLastPenaltyImposedDays mocks base method.
func (m *MockFirestoreController) UpdateUserLastPenaltyImposedDays(ctx context.Context, tx *firestore.Transaction, userId string, lastPenaltyImposedDays int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastPenaltyImposedDays", ctx, tx, userId, lastPenaltyImposedDays)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastPenaltyImposedDays indicates an expected call of UpdateUserLastPenaltyImposedDays.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserLastPenaltyImposedDays(ctx, tx, userId, lastPenaltyImposedDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastPenaltyImposedDays", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserLastPenaltyImposedDays), ctx, tx, userId, lastPenaltyImposedDays)
}

// UpdateUserLastRPProcessed mocks base method.
func (m *MockFirestoreController) UpdateUserLastRPProcessed(tx *firestore.Transaction, userId string, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastRPProcessed", tx, userId, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastRPProcessed indicates an expected call of UpdateUserLastRPProcessed.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserLastRPProcessed(tx, userId, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastRPProcessed", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserLastRPProcessed), tx, userId, date)
}

// UpdateUserRPAndLastPenaltyImposedDays mocks base method.
func (m *MockFirestoreController) UpdateUserRPAndLastPenaltyImposedDays(ctx context.Context, tx *firestore.Transaction, userId string, newRP, newLastPenaltyImposedDays int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRPAndLastPenaltyImposedDays", ctx, tx, userId, newRP, newLastPenaltyImposedDays)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRPAndLastPenaltyImposedDays indicates an expected call of UpdateUserRPAndLastPenaltyImposedDays.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserRPAndLastPenaltyImposedDays(ctx, tx, userId, newRP, newLastPenaltyImposedDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRPAndLastPenaltyImposedDays", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserRPAndLastPenaltyImposedDays), ctx, tx, userId, newRP, newLastPenaltyImposedDays)
}

// UpdateUserRankPoint mocks base method.
func (m *MockFirestoreController) UpdateUserRankPoint(tx *firestore.Transaction, userId string, rp int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRankPoint", tx, userId, rp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRankPoint indicates an expected call of UpdateUserRankPoint.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserRankPoint(tx, userId, rp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRankPoint", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserRankPoint), tx, userId, rp)
}

// UpdateUserRankVisible mocks base method.
func (m *MockFirestoreController) UpdateUserRankVisible(tx *firestore.Transaction, userId string, rankVisible bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRankVisible", tx, userId, rankVisible)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRankVisible indicates an expected call of UpdateUserRankVisible.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserRankVisible(tx, userId, rankVisible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRankVisible", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserRankVisible), tx, userId, rankVisible)
}

// UpdateUserTotalTime mocks base method.
func (m *MockFirestoreController) UpdateUserTotalTime(tx *firestore.Transaction, userId string, newTotalTimeSec, newDailyTotalTimeSec int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTotalTime", tx, userId, newTotalTimeSec, newDailyTotalTimeSec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserTotalTime indicates an expected call of UpdateUserTotalTime.
func (mr *MockFirestoreControllerMockRecorder) UpdateUserTotalTime(tx, userId, newTotalTimeSec, newDailyTotalTimeSec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTotalTime", reflect.TypeOf((*MockFirestoreController)(nil).UpdateUserTotalTime), tx, userId, newTotalTimeSec, newDailyTotalTimeSec)
}
