name: GoTest

on:
  pull_request:
    branches: [ main, release, dev ]
  push:
    branches: [ main, release, dev ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies and run tests
        run: |
          cd system
          go mod tidy
          go test -v ./...
