name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  system-go-test:
    name: System Go Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: system
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: system/go.mod
          cache: true
          cache-dependency-path: |
            system/go.sum
            system/go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -shuffle=on -v ./...

  youtube-monitor-test:
    name: YouTube Monitor Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: youtube-monitor
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: youtube-monitor/package.json
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: youtube-monitor/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test

  aws-cdk-test:
    name: AWS CDK Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: aws-cdk
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: aws-cdk/package.json
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: aws-cdk/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
